<?php

class ModulaSettings {
  private $type;
  private $grid_type;
  private $grid_row_height;
  private $grid_justify_last_row;
  private $grid_image_size;
  private $grid_image_dimensions;
  private $img_size;
  private $img_crop;
  private $grid_image_crop;
  private $gutter;
  private $tablet_gutter;
  private $mobile_gutter;
  private $width;
  private $height;
  private $randomFactor;
  private $shuffle;
  private $lightbox;
  private $show_navigation;
  private $hide_title;
  private $titleColor;
  private $titleFontSize;
  private $mobileTitleFontSize;
  private $hide_description;
  private $captionColor;
  private $captionFontSize;
  private $mobileCaptionFontSize;
  private $enableSocial;
  private $enableTwitter;
  private $enableFacebook;
  private $enableWhatsapp;
  private $enableLinkedin;
  private $enablePinterest;
  private $enableEmail;
  private $emailSubject;
  private $emailMessage;
  private $socialIconColor;
  private $socialIconSize;
  private $socialIconPadding;
  private $loadedScale;
  private $inView;
  private $effect;
  private $cursor;
  private $borderSize;
  private $borderRadius;
  private $borderColor;
  private $shadowSize;
  private $shadowColor;
  private $lazy_load;
  private $enable_responsive;
  private $tablet_columns;
  private $mobile_columns;
  private $style;
  private $last_visited_tab;
  private $upload_position;

  public function __construct(string $filename, int $id){
    $this->borderColor = "#ffffff";
    $this->borderRadius = 0;
    $this->borderSize = 0;
    $this->captionColor = "#ffffff";
    $this->captionFontSize = 14;
    $this->cursor = "zoom-in";
    $this->effect = "pufrobo";
    $this->emailMessage = "here is the link to the image : %%image_link%% and this is the link to the gallery : %%gallery_link%%";
    $this->emailSubject = "check out this awesome image !!";
    $this->enable_responsive = "0";
    $this->enableEmail = "0";
    $this->enableFacebook = "0";
    $this->enableLinkedin = "0";
    $this->enablePinterest = "0";
    $this->enableSocial = "0";
    $this->enableTwitter = "0";
    $this->enableWhatsapp = "0";
    $this->grid_image_crop = "0";
    $this->grid_image_dimensions = ["width" => 0,"height" => 0];
    $this->grid_image_size = "medium";
    $this->grid_justify_last_row = "justify";
    $this->grid_row_height = 250;
    $this->grid_type = "automatic";
    $this->gutter = 10;
    $this->height = [800, 800, 800];
    $this->hide_description = "0";
    $this->hide_title = true;
    $this->img_crop = true;
    $this->img_size = 200;
    $this->inView = "0";
    $this->last_visited_tab = "modula-general";
    $this->lazy_load = true;
    $this->lightbox = "fancybox";
    $this->loadedScale = 100;
    $this->mobile_columns = 1;
    $this->mobile_gutter = 10;
    $this->mobileCaptionFontSize = 10;
    $this->mobileTitleFontSize = 12;
    $this->randomFactor = 50;
    $this->shadowColor = "#ffffff";
    $this->shadowSize = 0;
    $this->show_navigation = true;
    $this->shuffle = "0";
    $this->socialIconColor = "#ffffff";
    $this->socialIconPadding = 10;
    $this->socialIconSize = 16;
    $this->style = "";
    $this->tablet_columns = 2;
    $this->tablet_gutter = 10;
    $this->titleColor = "#ffffff";
    $this->titleFontSize = 16;
    $this->type = "grid";
    $this->upload_position = "end";
    $this->width = "100%";
  }
}